/**
 * Mock data for full analysis detail view
 * Based on XNCR_20260226T0853.yaml structure
 */

import type { AnalysisDetail } from '@/types/analysis';

export const mockAnalysisDetails: Record<string, AnalysisDetail> = {
  'NVDA': {
    _meta: {
      id: 'NVDA_20260228T1000',
      type: 'stock-analysis',
      version: '2.6',
      created: '2026-02-28T10:00:00-05:00',
      status: 'active',
    },
    ticker: 'NVDA',
    current_price: 875.50,
    analysis_date: '2026-02-28',
    analysis_type: 'momentum',
    setup: {
      fifty_two_week_high: 974.00,
      fifty_two_week_low: 475.00,
      distance_from_ath_pct: -10.1,
      distance_from_52w_low_pct: 84.3,
      market_cap_b: 2150.0,
      pe_ttm: 65.0,
      pe_forward: 45.0,
      next_earnings_date: '2026-05-20',
      days_to_earnings: 81,
      ytd_return_pct: 28.5,
    },
    catalyst: {
      type: 'earnings_momentum',
      description: 'Post-earnings momentum + AI chip demand acceleration',
      specificity: 'high',
      timing: 'near_term',
      catalyst_score: 8,
      reasoning: 'NVDA continues to benefit from AI infrastructure buildout. Recent earnings showed 200%+ YoY growth in data center revenue.',
    },
    market_environment: {
      regime: 'bull',
      sector: 'Semiconductors',
      sector_trend: 'bullish',
      vix_level: 14.5,
      vix_environment: 'low',
      environment_score: 8,
    },
    threat_assessment: {
      primary_concern: 'low',
      structural_threat: { exists: false, description: '' },
      cyclical_weakness: { exists: false },
      threat_summary: 'No immediate structural threats. Competition from AMD and custom AI chips is manageable given CUDA ecosystem moat. Supply constraints easing.',
    },
    scenarios: {
      strong_bull: { probability: 25, description: 'AI demand exceeds expectations', target_price: 1100, return_pct: 25.6, timeline_days: 90, key_driver: 'Data center revenue acceleration' },
      base_bull: { probability: 40, description: 'Continued AI momentum', target_price: 950, return_pct: 8.5, timeline_days: 60, key_driver: 'Steady growth trajectory' },
      base_bear: { probability: 25, description: 'Consolidation after run-up', target_price: 820, return_pct: -6.3, timeline_days: 45, key_driver: 'Profit-taking, sector rotation' },
      strong_bear: { probability: 10, description: 'AI spending pullback', target_price: 700, return_pct: -20.0, timeline_days: 90, key_driver: 'Macro concerns, China restrictions' },
      expected_value: 12.5,
    },
    bull_case_analysis: {
      strength: 8,
      arguments: [
        { argument: 'AI infrastructure buildout accelerating', score: 9, evidence: 'Hyperscalers increasing capex 40%+', counter: 'Could slow in 2027', counter_strength: 4 },
        { argument: 'CUDA ecosystem lock-in', score: 8, evidence: 'Developers prefer NVIDIA', counter: 'Open alternatives emerging', counter_strength: 5 },
        { argument: 'Blackwell architecture advantages', score: 8, evidence: '4x inference performance', counter: 'Execution risk on new arch', counter_strength: 4 },
      ],
      summary: 'NVDA dominates AI compute with 80%+ market share and strong moat.',
      strongest_argument: 'AI infrastructure buildout accelerating',
    },
    base_case_analysis: {
      strength: 6,
      arguments: [
        { argument: 'Valuation stretched at 45x forward', score: 6, evidence: 'Premium to historical average', counter: 'Growth justifies premium', counter_strength: 6 },
        { argument: 'Competition increasing', score: 5, evidence: 'AMD MI300X gaining traction', counter: 'Still small share', counter_strength: 5 },
      ],
      summary: 'Growth continues but at moderating pace as comparisons get harder.',
      strongest_argument: 'Valuation stretched at 45x forward',
    },
    bear_case_analysis: {
      strength: 4,
      arguments: [
        { argument: 'Customer concentration risk', score: 5, evidence: 'Top 4 customers = 40% revenue', counter: 'Diversifying rapidly', counter_strength: 6 },
        { argument: 'China revenue at risk', score: 6, evidence: 'Export restrictions tightening', counter: 'Only 10-15% of revenue', counter_strength: 5 },
      ],
      summary: 'Bear case relies on macro shock or regulatory action.',
      strongest_argument: 'China revenue at risk from export restrictions',
    },
    comparable_companies: {
      peers: [
        { ticker: 'AMD', name: 'Advanced Micro Devices', pe_forward: 35.0, ps_ratio: 12.5, ev_ebitda: 28.0, revenue_growth_pct: 45.0, market_cap_b: 280.0 },
        { ticker: 'AVGO', name: 'Broadcom Inc', pe_forward: 25.0, ps_ratio: 15.0, ev_ebitda: 22.0, revenue_growth_pct: 35.0, market_cap_b: 620.0 },
        { ticker: 'MRVL', name: 'Marvell Technology', pe_forward: 40.0, ps_ratio: 10.0, ev_ebitda: 30.0, revenue_growth_pct: 25.0, market_cap_b: 65.0 },
        { ticker: 'INTC', name: 'Intel Corp', pe_forward: 20.0, ps_ratio: 2.5, ev_ebitda: 8.0, revenue_growth_pct: -5.0, market_cap_b: 180.0 },
      ],
      sector_median_pe: 30.0,
      sector_median_ps: 11.0,
      sector_median_ev_ebitda: 25.0,
      valuation_position: 'premium',
      discount_premium_pct: 50.0,
      valuation_notes: 'NVDA trades at significant premium to peers, justified by growth rate and market position.',
    },
    liquidity_analysis: {
      adv_shares: 35000000,
      adv_dollars: 30000000000,
      adv_percentile: 99,
      bid_ask_spread_pct: 0.01,
      spread_environment: 'tight',
      slippage_estimate_pct: 0.02,
      liquidity_score: 10,
      execution_notes: 'Highly liquid. No execution concerns for any reasonable position size.',
    },
    sentiment: {
      analyst: { buy: 45, hold: 8, sell: 2, avg_target: 1050.0, implied_upside_pct: 20.0 },
      short_interest: { pct_float: 1.2, days_to_cover: 0.8, trend: 'declining' },
      options: { put_call_ratio: 0.65, iv_percentile: 55, iv_rank: 50, unusual_flow: 'bullish_calls' },
    },
    fundamentals: {
      valuation: { pe_ratio: 65.0, pe_forward: 45.0, ps_ratio: 35.0, ev_ebitda: 55.0 },
      growth: { revenue_growth_yoy: 120.0, earnings_growth_yoy: 180.0 },
      quality: { profit_margin: 55.0, operating_margin: 60.0, roe: 85.0, debt_to_equity: 0.4, cash_position_b: 25.0 },
    },
    bias_check: {
      recency_bias: { detected: true, severity: 'low' },
      confirmation_bias: { detected: false, severity: 'none' },
      anchoring: { detected: true, severity: 'low' },
      fomo: { detected: false, severity: 'none' },
      overconfidence: { detected: false, severity: 'none' },
      bias_summary: 'Minor recency and anchoring bias from recent strong performance. Countermeasures applied.',
    },
    do_nothing_gate: {
      ev_threshold: 5.0,
      ev_actual: 12.5,
      ev_passes: true,
      confidence_threshold: 60,
      confidence_actual: 75,
      confidence_passes: true,
      rr_threshold: 2.0,
      rr_actual: 3.2,
      rr_passes: true,
      edge_exists: true,
      edge_description: 'AI infrastructure buildout provides structural tailwind not fully priced',
      gates_passed: 4,
      gate_result: 'PASS',
      gate_reasoning: 'All 4 gate criteria passed. Strong conviction setup.',
    },
    alert_levels: {
      price_alerts: [
        { price: 900.0, direction: 'above', significance: 'Breakout confirmation', action_if_triggered: 'Add to position', alert_active: true, tag: 'Breakout' },
        { price: 820.0, direction: 'below', significance: 'Support break', action_if_triggered: 'Reduce position', alert_active: true, tag: 'Support' },
        { price: 950.0, direction: 'above', significance: 'Target 1 reached', action_if_triggered: 'Take 1/3 profits', alert_active: true, tag: 'Target 1' },
      ],
      event_alerts: [
        { event: 'Q2 2026 Earnings', date: '2026-05-20', action: 'Review position sizing' },
        { event: 'GTC Conference', date: '2026-03-18', action: 'Watch for product announcements' },
      ],
      post_event_review: '2026-03-15',
    },
    falsification: {
      criteria: [
        { condition: 'Data center revenue growth decelerates below 50%', current_value: '200%+', threshold: '<50%' },
        { condition: 'AMD gains significant share', current_value: '5%', threshold: '>20%' },
      ],
      thesis_invalid_if: 'Data center revenue growth falls below 50% YoY or China restrictions expand significantly.',
      review_triggers: ['Earnings reports', 'Competitor product launches', 'Regulatory announcements'],
    },
    scoring: {
      catalyst_score: 8,
      environment_score: 8,
      technical_score: 7,
      risk_reward_score: 7,
      sentiment_score: 8,
      weighted_total: 7.6,
    },
    confidence: {
      level: 75,
      rationale: 'Strong structural thesis with multiple confirmation points',
    },
    recommendation: 'BUY',
    rationale: 'NVDA remains the best positioned company for AI infrastructure buildout. While valuation is elevated, growth trajectory justifies premium. The CUDA ecosystem moat provides defensible market position. Recommend maintaining or adding to position on any weakness.',
    alternative_strategies: {
      applicable: true,
      strategies: [
        { strategy: 'Buy dips to 50-day MA', trigger: 'Price touches $840', entry_zone: '$830-$850', rationale: 'Better risk/reward entry' },
        { strategy: 'Sell put spreads', trigger: 'IV spike >70 percentile', entry_zone: 'N/A', rationale: 'Generate income while waiting' },
        { strategy: 'Call calendar spread', trigger: 'GTC conference approach', entry_zone: 'N/A', rationale: 'Play event with defined risk' },
      ],
      best_alternative: 'Buy dips to 50-day MA',
      best_alternative_rationale: 'Provides better risk/reward without chasing current levels',
    },
    meta_learning: {
      pattern_identified: 'Post-earnings drift in mega-cap tech',
      similar_setup: 'Similar to MSFT Feb 2025 post-earnings continuation',
    },
    news_age_check: {
      items: [
        { news_item: 'Q4 earnings beat expectations', date: '2026-02-21', age_weeks: 1, priced_in: 'partially' },
        { news_item: 'Blackwell production ramp confirmed', date: '2026-02-15', age_weeks: 2, priced_in: 'mostly' },
      ],
      stale_news_risk: false,
      fresh_catalyst_exists: true,
    },
  },
  'AAPL': {
    _meta: {
      id: 'AAPL_20260227T1430',
      type: 'stock-analysis',
      version: '2.6',
      created: '2026-02-27T14:30:00-05:00',
      status: 'active',
    },
    ticker: 'AAPL',
    current_price: 182.30,
    analysis_date: '2026-02-27',
    analysis_type: 'earnings_preview',
    setup: {
      fifty_two_week_high: 199.62,
      fifty_two_week_low: 164.08,
      distance_from_ath_pct: -8.7,
      distance_from_52w_low_pct: 11.1,
      market_cap_b: 2850.0,
      pe_ttm: 28.5,
      pe_forward: 26.0,
      next_earnings_date: '2026-04-30',
      days_to_earnings: 62,
      ytd_return_pct: 4.2,
    },
    catalyst: {
      type: 'product_cycle',
      description: 'iPhone 17 launch cycle approaching; Services growth acceleration',
      specificity: 'medium',
      timing: 'near_term',
      catalyst_score: 6,
      reasoning: 'AAPL entering new product cycle with iPhone 17. Services segment growing 15%+ provides earnings stability.',
    },
    market_environment: {
      regime: 'bull',
      sector: 'Consumer Electronics',
      sector_trend: 'neutral',
      vix_level: 15.2,
      vix_environment: 'low',
      environment_score: 6,
    },
    threat_assessment: {
      primary_concern: 'moderate',
      structural_threat: { exists: false, description: '' },
      cyclical_weakness: { exists: true },
      threat_summary: 'China sales remain weak. iPhone replacement cycle lengthening. Services growth offsetting hardware slowdown.',
    },
    scenarios: {
      strong_bull: { probability: 20, description: 'China recovery + strong iPhone 17', target_price: 210, return_pct: 15.2, timeline_days: 120, key_driver: 'China demand rebound' },
      base_bull: { probability: 35, description: 'Modest growth, Services strength', target_price: 195, return_pct: 7.0, timeline_days: 90, key_driver: 'Services margin expansion' },
      base_bear: { probability: 35, description: 'Flat iPhone sales, China weakness', target_price: 175, return_pct: -4.0, timeline_days: 60, key_driver: 'Macro weakness impact' },
      strong_bear: { probability: 10, description: 'China ban or major demand shock', target_price: 155, return_pct: -15.0, timeline_days: 90, key_driver: 'Geopolitical escalation' },
      expected_value: 6.2,
    },
    bull_case_analysis: {
      strength: 6,
      arguments: [
        { argument: 'Services growing 15%+ with expanding margins', score: 7, evidence: 'App Store, subscriptions accelerating', counter: 'Regulatory pressure on App Store', counter_strength: 5 },
        { argument: 'Strong balance sheet for buybacks', score: 7, evidence: '$100B+ annual buyback capacity', counter: 'Already at historical highs', counter_strength: 4 },
      ],
      summary: 'Services growth provides stability; new product cycle could reignite hardware growth.',
      strongest_argument: 'Services segment growing with expanding margins',
    },
    base_case_analysis: {
      strength: 7,
      arguments: [
        { argument: 'Mature hardware business with flat growth', score: 6, evidence: 'iPhone sales flat YoY', counter: 'New cycle could change', counter_strength: 5 },
        { argument: 'China headwinds persist', score: 6, evidence: 'Market share declining', counter: 'Stabilizing recently', counter_strength: 5 },
      ],
      summary: 'Base case is steady state - modest growth driven by Services with flat hardware.',
      strongest_argument: 'Mature business with limited growth catalysts',
    },
    bear_case_analysis: {
      strength: 5,
      arguments: [
        { argument: 'China regulatory risk', score: 6, evidence: 'Government app restrictions', counter: 'Limited revenue impact so far', counter_strength: 6 },
        { argument: 'Antitrust pressure on App Store', score: 5, evidence: 'EU DMA requirements', counter: 'Minimal revenue impact expected', counter_strength: 6 },
      ],
      summary: 'Bear case requires external shock - regulatory action or major China escalation.',
      strongest_argument: 'China regulatory and competitive risk',
    },
    comparable_companies: {
      peers: [
        { ticker: 'MSFT', name: 'Microsoft Corp', pe_forward: 32.0, ps_ratio: 12.0, ev_ebitda: 24.0, revenue_growth_pct: 15.0, market_cap_b: 3100.0 },
        { ticker: 'GOOGL', name: 'Alphabet Inc', pe_forward: 22.0, ps_ratio: 6.5, ev_ebitda: 16.0, revenue_growth_pct: 12.0, market_cap_b: 1950.0 },
        { ticker: 'AMZN', name: 'Amazon.com', pe_forward: 45.0, ps_ratio: 3.2, ev_ebitda: 18.0, revenue_growth_pct: 11.0, market_cap_b: 1850.0 },
      ],
      sector_median_pe: 28.0,
      sector_median_ps: 7.0,
      sector_median_ev_ebitda: 19.0,
      valuation_position: 'inline',
      discount_premium_pct: 0.0,
      valuation_notes: 'AAPL trades in-line with mega-cap tech peers. Premium justified by cash flow and buybacks.',
    },
    liquidity_analysis: {
      adv_shares: 50000000,
      adv_dollars: 9000000000,
      adv_percentile: 99,
      bid_ask_spread_pct: 0.01,
      spread_environment: 'tight',
      slippage_estimate_pct: 0.01,
      liquidity_score: 10,
      execution_notes: 'Most liquid stock in the market. No execution concerns.',
    },
    sentiment: {
      analyst: { buy: 32, hold: 18, sell: 3, avg_target: 205.0, implied_upside_pct: 12.5 },
      short_interest: { pct_float: 0.8, days_to_cover: 0.5, trend: 'stable' },
      options: { put_call_ratio: 0.75, iv_percentile: 40, iv_rank: 35, unusual_flow: 'none' },
    },
    fundamentals: {
      valuation: { pe_ratio: 28.5, pe_forward: 26.0, ps_ratio: 7.5, ev_ebitda: 22.0 },
      growth: { revenue_growth_yoy: 3.0, earnings_growth_yoy: 8.0 },
      quality: { profit_margin: 25.0, operating_margin: 30.0, roe: 150.0, debt_to_equity: 1.8, cash_position_b: 65.0 },
    },
    bias_check: {
      recency_bias: { detected: false, severity: 'none' },
      confirmation_bias: { detected: true, severity: 'low' },
      anchoring: { detected: true, severity: 'medium' },
      fomo: { detected: false, severity: 'none' },
      overconfidence: { detected: false, severity: 'none' },
      bias_summary: 'Anchoring to historical highs. Need to consider current growth rate justification.',
    },
    do_nothing_gate: {
      ev_threshold: 5.0,
      ev_actual: 6.2,
      ev_passes: true,
      confidence_threshold: 60,
      confidence_actual: 65,
      confidence_passes: true,
      rr_threshold: 2.0,
      rr_actual: 1.8,
      rr_passes: false,
      edge_exists: true,
      edge_description: 'Services growth underappreciated; new product cycle approaching',
      gates_passed: 3,
      gate_result: 'MARGINAL',
      gate_reasoning: 'Risk/reward slightly below threshold. Marginal setup - proceed with smaller position.',
    },
    alert_levels: {
      price_alerts: [
        { price: 190.0, direction: 'above', significance: 'Breakout above resistance', action_if_triggered: 'Add to position', alert_active: true },
        { price: 170.0, direction: 'below', significance: 'Support break', action_if_triggered: 'Exit position', alert_active: true },
        { price: 200.0, direction: 'above', significance: 'Near ATH', action_if_triggered: 'Take profits', alert_active: true },
      ],
      event_alerts: [
        { event: 'Q2 2026 Earnings', date: '2026-04-30', action: 'Review iPhone sales data' },
        { event: 'WWDC 2026', date: '2026-06-10', action: 'Watch for AI announcements' },
      ],
      post_event_review: '2026-03-10',
    },
    falsification: {
      criteria: [
        { condition: 'Services growth decelerates below 10%', current_value: '15%', threshold: '<10%' },
        { condition: 'China revenue declines >15% YoY', current_value: '-8%', threshold: '>-15%' },
      ],
      thesis_invalid_if: 'Services growth stalls or China regulatory action significantly impacts operations.',
      review_triggers: ['Earnings reports', 'China regulatory news', 'Product announcements'],
    },
    scoring: {
      catalyst_score: 6,
      environment_score: 6,
      technical_score: 5,
      risk_reward_score: 5,
      sentiment_score: 6,
      weighted_total: 5.6,
    },
    confidence: {
      level: 65,
      rationale: 'Moderate confidence due to mixed growth signals',
    },
    recommendation: 'WATCH',
    rationale: 'AAPL is a quality compounder but current setup offers limited near-term upside. Services growth is positive but hardware weakness persists. Recommend watching for better entry on pullback to $170-175 range or confirmation of iPhone 17 demand strength.',
    pass_reasoning: {
      applicable: true,
      primary_reason: 'Risk/reward below threshold at current levels',
      reasons: [
        { reason: 'R:R ratio of 1.8 below 2.0 threshold', impact: 'H' },
        { reason: 'Limited near-term catalysts before Q2 earnings', impact: 'M' },
        { reason: 'China uncertainty persists', impact: 'M' },
      ],
      summary: 'Waiting for better entry point. Quality company but timing not optimal.',
    },
    alternative_strategies: {
      applicable: true,
      strategies: [
        { strategy: 'Buy pullback to $170-175', trigger: 'Price retraces to support', entry_zone: '$170-$175', rationale: 'Better risk/reward' },
        { strategy: 'Sell puts at $170 strike', trigger: 'IV above 30%', entry_zone: 'N/A', rationale: 'Get paid to wait for entry' },
      ],
      best_alternative: 'Buy pullback to $170-175',
      best_alternative_rationale: 'Improves risk/reward to acceptable levels',
    },
    meta_learning: {
      pattern_identified: 'Mega-cap consolidation before product cycle',
    },
    news_age_check: {
      items: [
        { news_item: 'Q1 earnings in-line', date: '2026-01-30', age_weeks: 4, priced_in: 'fully' },
      ],
      stale_news_risk: true,
      fresh_catalyst_exists: false,
    },
  },
  'MSFT': {
    _meta: {
      id: 'MSFT_20260226T0900',
      type: 'stock-analysis',
      version: '2.6',
      created: '2026-02-26T09:00:00-05:00',
      status: 'expired',
    },
    ticker: 'MSFT',
    current_price: 415.50,
    analysis_date: '2026-02-26',
    analysis_type: 'technical',
    setup: {
      fifty_two_week_high: 435.00,
      fifty_two_week_low: 362.90,
      distance_from_ath_pct: -4.5,
      distance_from_52w_low_pct: 14.5,
      market_cap_b: 3100.0,
      pe_ttm: 35.0,
      pe_forward: 32.0,
      next_earnings_date: '2026-04-22',
      days_to_earnings: 55,
      ytd_return_pct: 8.5,
    },
    catalyst: {
      type: 'none',
      description: 'No near-term catalyst identified',
      specificity: 'low',
      timing: 'none',
      catalyst_score: 3,
      reasoning: 'MSFT is executing well but no specific near-term catalyst. Cloud growth remains strong.',
    },
    market_environment: {
      regime: 'bull',
      sector: 'Software',
      sector_trend: 'bullish',
      vix_level: 15.0,
      vix_environment: 'low',
      environment_score: 7,
    },
    threat_assessment: {
      primary_concern: 'low',
      structural_threat: { exists: false, description: '' },
      cyclical_weakness: { exists: false },
      threat_summary: 'Strong competitive position. Azure growing. Copilot monetization progressing. No immediate concerns.',
    },
    scenarios: {
      strong_bull: { probability: 15, description: 'AI monetization exceeds expectations', target_price: 480, return_pct: 15.5, timeline_days: 120, key_driver: 'Copilot revenue surprise' },
      base_bull: { probability: 40, description: 'Steady cloud growth', target_price: 440, return_pct: 5.9, timeline_days: 90, key_driver: 'Azure 25%+ growth' },
      base_bear: { probability: 35, description: 'Growth deceleration', target_price: 400, return_pct: -3.7, timeline_days: 60, key_driver: 'Enterprise spending pause' },
      strong_bear: { probability: 10, description: 'Cloud competition intensifies', target_price: 370, return_pct: -11.0, timeline_days: 90, key_driver: 'AWS/GCP share gains' },
      expected_value: 2.1,
    },
    bull_case_analysis: {
      strength: 6,
      arguments: [
        { argument: 'Azure growing 25%+', score: 7, evidence: 'Consistent cloud share gains', counter: 'Growth decelerating', counter_strength: 5 },
        { argument: 'Copilot monetization starting', score: 6, evidence: 'Enterprise adoption ramping', counter: 'ROI not yet proven', counter_strength: 6 },
      ],
      summary: 'Quality business executing well but growth moderating.',
      strongest_argument: 'Azure cloud growth remains strong',
    },
    base_case_analysis: {
      strength: 7,
      arguments: [
        { argument: 'Mature mega-cap with limited re-rating potential', score: 7, evidence: 'Already trading near highs', counter: 'Quality deserves premium', counter_strength: 5 },
      ],
      summary: 'Steady compounder but limited upside at current valuation.',
      strongest_argument: 'Limited re-rating potential at current levels',
    },
    bear_case_analysis: {
      strength: 4,
      arguments: [
        { argument: 'Enterprise spending could slow', score: 5, evidence: 'Some CFO surveys show caution', counter: 'MSFT is essential spend', counter_strength: 7 },
      ],
      summary: 'Bear case requires significant macro deterioration.',
      strongest_argument: 'Enterprise spending sensitivity',
    },
    comparable_companies: {
      peers: [
        { ticker: 'AAPL', name: 'Apple Inc', pe_forward: 26.0, ps_ratio: 7.5, ev_ebitda: 22.0, revenue_growth_pct: 3.0, market_cap_b: 2850.0 },
        { ticker: 'GOOGL', name: 'Alphabet Inc', pe_forward: 22.0, ps_ratio: 6.5, ev_ebitda: 16.0, revenue_growth_pct: 12.0, market_cap_b: 1950.0 },
        { ticker: 'AMZN', name: 'Amazon.com', pe_forward: 45.0, ps_ratio: 3.2, ev_ebitda: 18.0, revenue_growth_pct: 11.0, market_cap_b: 1850.0 },
      ],
      sector_median_pe: 28.0,
      sector_median_ps: 6.0,
      sector_median_ev_ebitda: 18.0,
      valuation_position: 'premium',
      discount_premium_pct: 15.0,
      valuation_notes: 'MSFT trades at premium to peers reflecting quality and cloud position.',
    },
    liquidity_analysis: {
      adv_shares: 20000000,
      adv_dollars: 8300000000,
      adv_percentile: 99,
      bid_ask_spread_pct: 0.01,
      spread_environment: 'tight',
      slippage_estimate_pct: 0.01,
      liquidity_score: 10,
      execution_notes: 'Highly liquid. No execution concerns.',
    },
    sentiment: {
      analyst: { buy: 40, hold: 10, sell: 1, avg_target: 460.0, implied_upside_pct: 10.7 },
      short_interest: { pct_float: 0.6, days_to_cover: 0.4, trend: 'stable' },
      options: { put_call_ratio: 0.70, iv_percentile: 35, iv_rank: 30, unusual_flow: 'none' },
    },
    fundamentals: {
      valuation: { pe_ratio: 35.0, pe_forward: 32.0, ps_ratio: 13.0, ev_ebitda: 25.0 },
      growth: { revenue_growth_yoy: 15.0, earnings_growth_yoy: 18.0 },
      quality: { profit_margin: 35.0, operating_margin: 42.0, roe: 35.0, debt_to_equity: 0.4, cash_position_b: 80.0 },
    },
    bias_check: {
      recency_bias: { detected: false, severity: 'none' },
      confirmation_bias: { detected: false, severity: 'none' },
      anchoring: { detected: false, severity: 'none' },
      fomo: { detected: false, severity: 'none' },
      overconfidence: { detected: false, severity: 'none' },
      bias_summary: 'No significant biases detected. Analysis conducted objectively.',
    },
    do_nothing_gate: {
      ev_threshold: 5.0,
      ev_actual: 2.1,
      ev_passes: false,
      confidence_threshold: 60,
      confidence_actual: 55,
      confidence_passes: false,
      rr_threshold: 2.0,
      rr_actual: 1.2,
      rr_passes: false,
      edge_exists: false,
      edge_description: 'No clear edge at current valuation',
      gates_passed: 0,
      gate_result: 'FAIL',
      gate_reasoning: 'No gates passed. Quality company but no edge at current levels. Do not initiate position.',
    },
    alert_levels: {
      price_alerts: [
        { price: 440.0, direction: 'above', significance: 'New ATH', action_if_triggered: 'Reassess thesis', alert_active: false },
        { price: 390.0, direction: 'below', significance: 'Support level', action_if_triggered: 'Consider entry', alert_active: true },
      ],
      event_alerts: [
        { event: 'Q3 2026 Earnings', date: '2026-04-22', action: 'Review Azure growth' },
      ],
      post_event_review: '2026-03-05',
    },
    falsification: {
      criteria: [
        { condition: 'Azure growth below 20%', current_value: '25%', threshold: '<20%' },
      ],
      thesis_invalid_if: 'No current thesis to invalidate - waiting for better entry.',
      review_triggers: ['Significant price decline', 'Earnings surprise'],
    },
    scoring: {
      catalyst_score: 3,
      environment_score: 7,
      technical_score: 5,
      risk_reward_score: 3,
      sentiment_score: 6,
      weighted_total: 4.8,
    },
    confidence: {
      level: 55,
      rationale: 'Quality company but no edge at current valuation',
    },
    recommendation: 'NO_POSITION',
    rationale: 'MSFT is a high-quality compounder but offers insufficient risk-adjusted return at current levels. Expected value of 2.1% is below threshold. No near-term catalyst identified. Wait for pullback to $390-400 range for better entry opportunity.',
    pass_reasoning: {
      applicable: true,
      primary_reason: 'Insufficient risk-adjusted return at current valuation',
      reasons: [
        { reason: 'Expected value 2.1% below 5% threshold', impact: 'H' },
        { reason: 'No clear catalyst identified', impact: 'H' },
        { reason: 'Risk:reward 1.2:1 below threshold', impact: 'H' },
      ],
      summary: 'All gate criteria fail. Not a current opportunity despite quality.',
    },
    alternative_strategies: {
      applicable: true,
      strategies: [
        { strategy: 'Wait for pullback to $390-400', trigger: 'Price decline >5%', entry_zone: '$390-$400', rationale: 'Acceptable risk/reward' },
        { strategy: 'Monitor for catalyst emergence', trigger: 'New product announcement', entry_zone: 'TBD', rationale: 'Could change thesis' },
      ],
      best_alternative: 'Wait for pullback to $390-400',
      best_alternative_rationale: 'Would improve risk/reward to acceptable levels',
    },
    meta_learning: {
      pattern_identified: 'Quality at wrong price',
    },
    news_age_check: {
      items: [
        { news_item: 'Q2 earnings results', date: '2026-01-28', age_weeks: 4, priced_in: 'fully' },
      ],
      stale_news_risk: true,
      fresh_catalyst_exists: false,
    },
  },
};

// Helper to get analysis by ticker
export function getMockAnalysisDetail(ticker: string): AnalysisDetail | null {
  return mockAnalysisDetails[ticker.toUpperCase()] || null;
}

// Helper to list available mock analyses
export function getAvailableMockAnalyses(): string[] {
  return Object.keys(mockAnalysisDetails);
}
